import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = process.cwd();

let cached = null;

/**
 * Model artifact provenance (ML-02). Read once from Models/VERSION.json
 * (generated by scripts/gen-model-version.mjs, refreshed by the weekly
 * Kaggle pipeline). Falls back to a legacy literal when the file is absent
 * so local dev without artifacts still boots.
 */
export function getModelInfo() {
  if (cached) return cached;
  const candidates = [
    path.join(__dirname, '..', 'Models', 'VERSION.json'),
    path.join(__dirname, '..', 'models', 'VERSION.json'),
  ];
  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) {
        cached = JSON.parse(fs.readFileSync(p, 'utf8'));
        return cached;
      }
    } catch (err) {
      console.warn(`[modelInfo] Could not parse ${p}:`, err.message);
    }
  }
  cached = { version: '1.0-FP32 (legacy literal — VERSION.json missing)', artifacts: [] };
  return cached;
}
