/**
 * GENERATED FILE - do not edit.
 *
 * One icon family for both platforms, generated by scripts/generate-icon-glyphs.mjs from
 * data/design/icon-registry.json and lucide-react@1.48.0 (the one icon dependency the repo
 * declares). Web renders these names with `lucide-react`; the native shell renders the same path
 * data with `react-native-svg`, so an icon means the same thing on both.
 *
 * To add an icon: add its lucide name to the registry and run `npm run icons:build`.
 * `__tests__/iconFamily.test.js` fails if a call site imports a name that is not here.
 */

/** The decided family. Not a preference: the only icon package declared for this app. */
export const ICON_FAMILY = "lucide" as const;

/** The package that owns the glyph bodies on web. Native renders ICON_PATHS instead. */
export const ICON_PACKAGE = "lucide-react" as const;

/** Lucide's own version these paths were generated from. */
export const ICON_SOURCE_VERSION = "1.48.0" as const;

/**
 * One stroke weight for the whole app. Lucide's default is 2, which reads heavy next to
 * Meridian's hairlines (skill3 bans the thick-stroke look); at 1.75 the glyphs match the
 * 1px border weight and stay legible at 14-16px.
 */
export const ICON_STROKE = 1.75 as const;

/** Named sizes. The values are the same on web (px) and native (dp/pt). */
export const ICON_SIZES = {
  "inline": 14,
  "meta": 16,
  "control": 18,
  "nav": 20,
  "hero": 24,
  "display": 32
} as const;

/** Every icon name the app is allowed to use. */
export const ICON_NAMES = [
  "Activity",
  "AlertCircle",
  "AlertTriangle",
  "ArrowDown",
  "ArrowDownUp",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "BarChart3",
  "Bell",
  "BookOpen",
  "Bookmark",
  "BookmarkCheck",
  "Bot",
  "Box",
  "Building",
  "Building2",
  "Calendar",
  "Camera",
  "Check",
  "CheckCircle2",
  "ChevronDown",
  "ChevronRight",
  "ChevronUp",
  "Circle",
  "Clock",
  "Cloud",
  "CloudDownload",
  "CloudDrizzle",
  "CloudFog",
  "CloudHail",
  "CloudLightning",
  "CloudRain",
  "CloudRainWind",
  "CloudSnow",
  "CloudSun",
  "Compass",
  "Contrast",
  "Copy",
  "Cpu",
  "Crosshair",
  "Database",
  "Download",
  "Droplets",
  "ExternalLink",
  "Eye",
  "FileDown",
  "FileSpreadsheet",
  "FileText",
  "Filter",
  "Flame",
  "Gauge",
  "Globe",
  "HardDrive",
  "HelpCircle",
  "History",
  "Image",
  "Inbox",
  "Info",
  "Layers",
  "Loader2",
  "LogOut",
  "Mail",
  "MapPin",
  "Maximize",
  "Maximize2",
  "MessageSquare",
  "Mic",
  "MicOff",
  "Minimize2",
  "Moon",
  "Navigation",
  "Phone",
  "PhoneCall",
  "PhoneOff",
  "Printer",
  "QrCode",
  "Radio",
  "RefreshCw",
  "RotateCcw",
  "RotateCw",
  "Ruler",
  "Search",
  "Send",
  "Share2",
  "Shield",
  "ShieldAlert",
  "ShieldCheck",
  "Sliders",
  "SlidersHorizontal",
  "Smartphone",
  "Snowflake",
  "Sparkles",
  "Sprout",
  "Sun",
  "SunMedium",
  "Sunrise",
  "Sunset",
  "Thermometer",
  "ThermometerSun",
  "Trash2",
  "TrendingUp",
  "Umbrella",
  "Users",
  "Volume2",
  "VolumeX",
  "Waves",
  "Wheat",
  "Wifi",
  "WifiOff",
  "Wind",
  "X",
  "ZoomIn",
  "ZoomOut",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** `[tag, attributes]`, the subset of SVG the family uses. */
export type IconNode = readonly (readonly [string, Readonly<Record<string, string | number>>])[];

/**
 * Name -> glyph. Data only: no React, no DOM, so the native shell can consume it as-is.
 * The 24px grid and `viewBox="0 0 24 24"` are the family's contract on both platforms.
 */
export const ICON_PATHS: Readonly<Record<IconName, IconNode>> = {
  "Activity": [
    ["path", {"d":"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"}],
  ],
  "AlertCircle": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["line", {"x1":"12","x2":"12","y1":"8","y2":"12"}],
    ["line", {"x1":"12","x2":"12.01","y1":"16","y2":"16"}],
  ],
  "AlertTriangle": [
    ["path", {"d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"}],
    ["path", {"d":"M12 9v4"}],
    ["path", {"d":"M12 17h.01"}],
  ],
  "ArrowDown": [
    ["path", {"d":"M12 5v14"}],
    ["path", {"d":"m19 12-7 7-7-7"}],
  ],
  "ArrowDownUp": [
    ["path", {"d":"m3 16 4 4 4-4"}],
    ["path", {"d":"M7 20V4"}],
    ["path", {"d":"m21 8-4-4-4 4"}],
    ["path", {"d":"M17 4v16"}],
  ],
  "ArrowLeft": [
    ["path", {"d":"m12 19-7-7 7-7"}],
    ["path", {"d":"M19 12H5"}],
  ],
  "ArrowRight": [
    ["path", {"d":"M5 12h14"}],
    ["path", {"d":"m12 5 7 7-7 7"}],
  ],
  "ArrowUp": [
    ["path", {"d":"m5 12 7-7 7 7"}],
    ["path", {"d":"M12 19V5"}],
  ],
  "BarChart3": [
    ["path", {"d":"M3 3v16a2 2 0 0 0 2 2h16"}],
    ["path", {"d":"M18 17V9"}],
    ["path", {"d":"M13 17V5"}],
    ["path", {"d":"M8 17v-3"}],
  ],
  "Bell": [
    ["path", {"d":"M10.268 21a2 2 0 0 0 3.464 0"}],
    ["path", {"d":"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"}],
  ],
  "BookOpen": [
    ["path", {"d":"M12 5v16"}],
    ["path", {"d":"M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z"}],
  ],
  "Bookmark": [
    ["path", {"d":"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"}],
  ],
  "BookmarkCheck": [
    ["path", {"d":"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"}],
    ["path", {"d":"m9 10 2 2 4-4"}],
  ],
  "Bot": [
    ["path", {"d":"M12 8V4H8"}],
    ["rect", {"width":"16","height":"12","x":"4","y":"8","rx":"2"}],
    ["path", {"d":"M2 14h2"}],
    ["path", {"d":"M20 14h2"}],
    ["path", {"d":"M15 13v2"}],
    ["path", {"d":"M9 13v2"}],
  ],
  "Box": [
    ["path", {"d":"M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"}],
    ["path", {"d":"m3.3 7 8.7 5 8.7-5"}],
    ["path", {"d":"M12 22V12"}],
  ],
  "Building": [
    ["path", {"d":"M12 10h.01"}],
    ["path", {"d":"M12 14h.01"}],
    ["path", {"d":"M12 6h.01"}],
    ["path", {"d":"M16 10h.01"}],
    ["path", {"d":"M16 14h.01"}],
    ["path", {"d":"M16 6h.01"}],
    ["path", {"d":"M8 10h.01"}],
    ["path", {"d":"M8 14h.01"}],
    ["path", {"d":"M8 6h.01"}],
    ["path", {"d":"M9 22v-3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"}],
    ["rect", {"x":"4","y":"2","width":"16","height":"20","rx":"2"}],
  ],
  "Building2": [
    ["path", {"d":"M10 12h4"}],
    ["path", {"d":"M10 8h4"}],
    ["path", {"d":"M14 21v-3a2 2 0 0 0-4 0v3"}],
    ["path", {"d":"M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"}],
    ["path", {"d":"M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"}],
  ],
  "Calendar": [
    ["path", {"d":"M8 2v3"}],
    ["path", {"d":"M16 2v3"}],
    ["rect", {"x":"3","y":"3","width":"18","height":"18","rx":"2"}],
    ["path", {"d":"M3 9h18"}],
  ],
  "Camera": [
    ["path", {"d":"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z"}],
    ["circle", {"cx":"12","cy":"13","r":"3"}],
  ],
  "Check": [
    ["path", {"d":"M20 6 9 17l-5-5"}],
  ],
  "CheckCircle2": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"m16 9-5.5 5.5L8 12"}],
  ],
  "ChevronDown": [
    ["path", {"d":"m6 9 6 6 6-6"}],
  ],
  "ChevronRight": [
    ["path", {"d":"m9 18 6-6-6-6"}],
  ],
  "ChevronUp": [
    ["path", {"d":"m18 15-6-6-6 6"}],
  ],
  "Circle": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
  ],
  "Clock": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"M12 6v6l4 2"}],
  ],
  "Cloud": [
    ["path", {"d":"M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"}],
  ],
  "CloudDownload": [
    ["path", {"d":"M12 13v8l-4-4"}],
    ["path", {"d":"m12 21 4-4"}],
    ["path", {"d":"M4.393 15.269A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.436 8.284"}],
  ],
  "CloudDrizzle": [
    ["path", {"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],
    ["path", {"d":"M8 19v1"}],
    ["path", {"d":"M8 14v1"}],
    ["path", {"d":"M16 19v1"}],
    ["path", {"d":"M16 14v1"}],
    ["path", {"d":"M12 21v1"}],
    ["path", {"d":"M12 16v1"}],
  ],
  "CloudFog": [
    ["path", {"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],
    ["path", {"d":"M16 17H7"}],
    ["path", {"d":"M17 21H9"}],
  ],
  "CloudHail": [
    ["path", {"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],
    ["path", {"d":"M16 14v2"}],
    ["path", {"d":"M8 14v2"}],
    ["path", {"d":"M16 20h.01"}],
    ["path", {"d":"M8 20h.01"}],
    ["path", {"d":"M12 16v2"}],
    ["path", {"d":"M12 22h.01"}],
  ],
  "CloudLightning": [
    ["path", {"d":"M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 .5 8.973"}],
    ["path", {"d":"m13 12-3 5h4l-3 5"}],
  ],
  "CloudRain": [
    ["path", {"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],
    ["path", {"d":"M16 14v6"}],
    ["path", {"d":"M8 14v6"}],
    ["path", {"d":"M12 16v6"}],
  ],
  "CloudRainWind": [
    ["path", {"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],
    ["path", {"d":"m9.2 22 3-7"}],
    ["path", {"d":"m9 13-3 7"}],
    ["path", {"d":"m17 13-3 7"}],
  ],
  "CloudSnow": [
    ["path", {"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],
    ["path", {"d":"M8 15h.01"}],
    ["path", {"d":"M8 19h.01"}],
    ["path", {"d":"M12 17h.01"}],
    ["path", {"d":"M12 21h.01"}],
    ["path", {"d":"M16 15h.01"}],
    ["path", {"d":"M16 19h.01"}],
  ],
  "CloudSun": [
    ["path", {"d":"M12 2v2"}],
    ["path", {"d":"m4.93 4.93 1.41 1.41"}],
    ["path", {"d":"M20 12h2"}],
    ["path", {"d":"m19.07 4.93-1.41 1.41"}],
    ["path", {"d":"M15.947 12.65a4 4 0 0 0-5.925-4.128"}],
    ["path", {"d":"M13 22H7a5 5 0 1 1 4.9-6H13a3 3 0 0 1 0 6Z"}],
  ],
  "Compass": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z"}],
  ],
  "Contrast": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"M12 18a6 6 0 0 0 0-12v12z"}],
  ],
  "Copy": [
    ["rect", {"width":"14","height":"14","x":"8","y":"8","rx":"2","ry":"2"}],
    ["path", {"d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}],
  ],
  "Cpu": [
    ["path", {"d":"M12 20v2"}],
    ["path", {"d":"M12 2v2"}],
    ["path", {"d":"M17 20v2"}],
    ["path", {"d":"M17 2v2"}],
    ["path", {"d":"M2 12h2"}],
    ["path", {"d":"M2 17h2"}],
    ["path", {"d":"M2 7h2"}],
    ["path", {"d":"M20 12h2"}],
    ["path", {"d":"M20 17h2"}],
    ["path", {"d":"M20 7h2"}],
    ["path", {"d":"M7 20v2"}],
    ["path", {"d":"M7 2v2"}],
    ["rect", {"x":"4","y":"4","width":"16","height":"16","rx":"2"}],
    ["rect", {"x":"8","y":"8","width":"8","height":"8","rx":"1"}],
  ],
  "Crosshair": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["line", {"x1":"22","x2":"18","y1":"12","y2":"12"}],
    ["line", {"x1":"6","x2":"2","y1":"12","y2":"12"}],
    ["line", {"x1":"12","x2":"12","y1":"6","y2":"2"}],
    ["line", {"x1":"12","x2":"12","y1":"22","y2":"18"}],
  ],
  "Database": [
    ["ellipse", {"cx":"12","cy":"5","rx":"9","ry":"3"}],
    ["path", {"d":"M3 5V19A9 3 0 0 0 21 19V5"}],
    ["path", {"d":"M3 12A9 3 0 0 0 21 12"}],
  ],
  "Download": [
    ["path", {"d":"M12 15V3"}],
    ["path", {"d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}],
    ["path", {"d":"m7 10 5 5 5-5"}],
  ],
  "Droplets": [
    ["path", {"d":"M7 16.3c2.2 0 4-1.83 4-4.05 0-1.16-.57-2.26-1.71-3.19S7.29 6.75 7 5.3c-.29 1.45-1.14 2.84-2.29 3.76S3 11.1 3 12.25c0 2.22 1.8 4.05 4 4.05z"}],
    ["path", {"d":"M12.56 6.6A10.97 10.97 0 0 0 14 3.02c.5 2.5 2 4.9 4 6.5s3 3.5 3 5.5a6.98 6.98 0 0 1-11.91 4.97"}],
  ],
  "ExternalLink": [
    ["path", {"d":"M15 3h6v6"}],
    ["path", {"d":"M10 14 21 3"}],
    ["path", {"d":"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"}],
  ],
  "Eye": [
    ["path", {"d":"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"}],
    ["circle", {"cx":"12","cy":"12","r":"3"}],
  ],
  "FileDown": [
    ["path", {"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}],
    ["path", {"d":"M14 2v5a1 1 0 0 0 1 1h5"}],
    ["path", {"d":"M12 18v-6"}],
    ["path", {"d":"m9 15 3 3 3-3"}],
  ],
  "FileSpreadsheet": [
    ["path", {"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}],
    ["path", {"d":"M14 2v5a1 1 0 0 0 1 1h5"}],
    ["path", {"d":"M8 13h2"}],
    ["path", {"d":"M14 13h2"}],
    ["path", {"d":"M8 17h2"}],
    ["path", {"d":"M14 17h2"}],
  ],
  "FileText": [
    ["path", {"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}],
    ["path", {"d":"M14 2v5a1 1 0 0 0 1 1h5"}],
    ["path", {"d":"M10 9H8"}],
    ["path", {"d":"M16 13H8"}],
    ["path", {"d":"M16 17H8"}],
  ],
  "Filter": [
    ["path", {"d":"M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z"}],
  ],
  "Flame": [
    ["path", {"d":"M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4"}],
  ],
  "Gauge": [
    ["path", {"d":"m12 14 4-4"}],
    ["path", {"d":"M3.34 19a10 10 0 1 1 17.32 0"}],
  ],
  "Globe": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"}],
    ["path", {"d":"M2 12h20"}],
  ],
  "HardDrive": [
    ["path", {"d":"M10 16h.01"}],
    ["path", {"d":"M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"}],
    ["path", {"d":"M21.946 12.013H2.054"}],
    ["path", {"d":"M6 16h.01"}],
  ],
  "HelpCircle": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"}],
    ["path", {"d":"M12 17h.01"}],
  ],
  "History": [
    ["path", {"d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"}],
    ["path", {"d":"M3 3v5h5"}],
    ["path", {"d":"M12 7v5l4 2"}],
  ],
  "Image": [
    ["rect", {"width":"18","height":"18","x":"3","y":"3","rx":"2","ry":"2"}],
    ["circle", {"cx":"9","cy":"9","r":"2"}],
    ["path", {"d":"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}],
  ],
  "Inbox": [
    ["polyline", {"points":"22 12 16 12 14 15 10 15 8 12 2 12"}],
    ["path", {"d":"M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"}],
  ],
  "Info": [
    ["circle", {"cx":"12","cy":"12","r":"10"}],
    ["path", {"d":"M12 16v-4"}],
    ["path", {"d":"M12 8h.01"}],
  ],
  "Layers": [
    ["path", {"d":"M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z"}],
    ["path", {"d":"M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"}],
    ["path", {"d":"M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"}],
  ],
  "Loader2": [
    ["path", {"d":"M21 12a9 9 0 1 1-6.219-8.56"}],
  ],
  "LogOut": [
    ["path", {"d":"m16 17 5-5-5-5"}],
    ["path", {"d":"M21 12H9"}],
    ["path", {"d":"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"}],
  ],
  "Mail": [
    ["path", {"d":"m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"}],
    ["rect", {"x":"2","y":"4","width":"20","height":"16","rx":"2"}],
  ],
  "MapPin": [
    ["path", {"d":"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"}],
    ["circle", {"cx":"12","cy":"10","r":"3"}],
  ],
  "Maximize": [
    ["path", {"d":"M8 3H5a2 2 0 0 0-2 2v3"}],
    ["path", {"d":"M21 8V5a2 2 0 0 0-2-2h-3"}],
    ["path", {"d":"M3 16v3a2 2 0 0 0 2 2h3"}],
    ["path", {"d":"M16 21h3a2 2 0 0 0 2-2v-3"}],
  ],
  "Maximize2": [
    ["path", {"d":"M15 3h6v6"}],
    ["path", {"d":"m21 3-7 7"}],
    ["path", {"d":"m3 21 7-7"}],
    ["path", {"d":"M9 21H3v-6"}],
  ],
  "MessageSquare": [
    ["path", {"d":"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"}],
  ],
  "Mic": [
    ["path", {"d":"M12 19v3"}],
    ["path", {"d":"M19 10v2a7 7 0 0 1-14 0v-2"}],
    ["rect", {"x":"9","y":"2","width":"6","height":"13","rx":"3"}],
  ],
  "MicOff": [
    ["path", {"d":"M12 19v3"}],
    ["path", {"d":"M15 9.34V5a3 3 0 0 0-5.68-1.33"}],
    ["path", {"d":"M16.95 16.95A7 7 0 0 1 5 12v-2"}],
    ["path", {"d":"M18.89 13.23A7 7 0 0 0 19 12v-2"}],
    ["path", {"d":"m2 2 20 20"}],
    ["path", {"d":"M9 9v3a3 3 0 0 0 5.12 2.12"}],
  ],
  "Minimize2": [
    ["path", {"d":"m14 10 7-7"}],
    ["path", {"d":"M20 10h-6V4"}],
    ["path", {"d":"m3 21 7-7"}],
    ["path", {"d":"M4 14h6v6"}],
  ],
  "Moon": [
    ["path", {"d":"M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"}],
  ],
  "Navigation": [
    ["polygon", {"points":"3 11 22 2 13 21 11 13 3 11"}],
  ],
  "Phone": [
    ["path", {"d":"M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"}],
  ],
  "PhoneCall": [
    ["path", {"d":"M13 2a9 9 0 0 1 9 9"}],
    ["path", {"d":"M13 6a5 5 0 0 1 5 5"}],
    ["path", {"d":"M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"}],
  ],
  "PhoneOff": [
    ["path", {"d":"M10.1 13.9a14 14 0 0 0 3.732 2.668 1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2 18 18 0 0 1-12.728-5.272"}],
    ["path", {"d":"M22 2 2 22"}],
    ["path", {"d":"M4.76 13.582A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 .244.473"}],
  ],
  "Printer": [
    ["path", {"d":"M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"}],
    ["path", {"d":"M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6"}],
    ["rect", {"x":"6","y":"14","width":"12","height":"8","rx":"1"}],
  ],
  "QrCode": [
    ["rect", {"width":"5","height":"5","x":"3","y":"3","rx":"1"}],
    ["rect", {"width":"5","height":"5","x":"16","y":"3","rx":"1"}],
    ["rect", {"width":"5","height":"5","x":"3","y":"16","rx":"1"}],
    ["path", {"d":"M21 16h-3a2 2 0 0 0-2 2v3"}],
    ["path", {"d":"M21 21v.01"}],
    ["path", {"d":"M12 7v3a2 2 0 0 1-2 2H7"}],
    ["path", {"d":"M3 12h.01"}],
    ["path", {"d":"M12 3h.01"}],
    ["path", {"d":"M12 16v.01"}],
    ["path", {"d":"M16 12h1"}],
    ["path", {"d":"M21 12v.01"}],
    ["path", {"d":"M12 21v-1"}],
  ],
  "Radio": [
    ["path", {"d":"M16.247 7.761a6 6 0 0 1 0 8.478"}],
    ["path", {"d":"M19.075 4.933a10 10 0 0 1 0 14.134"}],
    ["path", {"d":"M4.925 19.067a10 10 0 0 1 0-14.134"}],
    ["path", {"d":"M7.753 16.239a6 6 0 0 1 0-8.478"}],
    ["circle", {"cx":"12","cy":"12","r":"2"}],
  ],
  "RefreshCw": [
    ["path", {"d":"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"}],
    ["path", {"d":"M21 3v5h-5"}],
    ["path", {"d":"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"}],
    ["path", {"d":"M8 16H3v5"}],
  ],
  "RotateCcw": [
    ["path", {"d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"}],
    ["path", {"d":"M3 3v5h5"}],
  ],
  "RotateCw": [
    ["path", {"d":"M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"}],
    ["path", {"d":"M21 3v5h-5"}],
  ],
  "Ruler": [
    ["path", {"d":"M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.41 2.41 0 0 1 0-3.4l2.6-2.6a2.41 2.41 0 0 1 3.4 0Z"}],
    ["path", {"d":"m14.5 12.5 2-2"}],
    ["path", {"d":"m11.5 9.5 2-2"}],
    ["path", {"d":"m8.5 6.5 2-2"}],
    ["path", {"d":"m17.5 15.5 2-2"}],
  ],
  "Search": [
    ["path", {"d":"m21 21-4.34-4.34"}],
    ["circle", {"cx":"11","cy":"11","r":"8"}],
  ],
  "Send": [
    ["path", {"d":"M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"}],
    ["path", {"d":"m21.854 2.147-10.94 10.939"}],
  ],
  "Share2": [
    ["circle", {"cx":"18","cy":"5","r":"3"}],
    ["circle", {"cx":"6","cy":"12","r":"3"}],
    ["circle", {"cx":"18","cy":"19","r":"3"}],
    ["line", {"x1":"8.59","x2":"15.42","y1":"13.51","y2":"17.49"}],
    ["line", {"x1":"15.41","x2":"8.59","y1":"6.51","y2":"10.49"}],
  ],
  "Shield": [
    ["path", {"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}],
  ],
  "ShieldAlert": [
    ["path", {"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}],
    ["path", {"d":"M12 8v4"}],
    ["path", {"d":"M12 16h.01"}],
  ],
  "ShieldCheck": [
    ["path", {"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}],
    ["path", {"d":"m9 12 2 2 4-4"}],
  ],
  "Sliders": [
    ["path", {"d":"M10 8h4"}],
    ["path", {"d":"M12 21v-9"}],
    ["path", {"d":"M12 8V3"}],
    ["path", {"d":"M17 16h4"}],
    ["path", {"d":"M19 12V3"}],
    ["path", {"d":"M19 21v-5"}],
    ["path", {"d":"M3 14h4"}],
    ["path", {"d":"M5 10V3"}],
    ["path", {"d":"M5 21v-7"}],
  ],
  "SlidersHorizontal": [
    ["path", {"d":"M10 5H3"}],
    ["path", {"d":"M12 19H3"}],
    ["path", {"d":"M14 3v4"}],
    ["path", {"d":"M16 17v4"}],
    ["path", {"d":"M21 12h-9"}],
    ["path", {"d":"M21 19h-5"}],
    ["path", {"d":"M21 5h-7"}],
    ["path", {"d":"M8 10v4"}],
    ["path", {"d":"M8 12H3"}],
  ],
  "Smartphone": [
    ["rect", {"width":"14","height":"20","x":"5","y":"2","rx":"2","ry":"2"}],
    ["path", {"d":"M12 18h.01"}],
  ],
  "Snowflake": [
    ["path", {"d":"m10 20-1.25-2.5L6 18"}],
    ["path", {"d":"M10 4 8.75 6.5 6 6"}],
    ["path", {"d":"m14 20 1.25-2.5L18 18"}],
    ["path", {"d":"m14 4 1.25 2.5L18 6"}],
    ["path", {"d":"m17 21-3-6h-4"}],
    ["path", {"d":"m17 3-3 6 1.5 3"}],
    ["path", {"d":"M2 12h6.5L10 9"}],
    ["path", {"d":"m20 10-1.5 2 1.5 2"}],
    ["path", {"d":"M22 12h-6.5L14 15"}],
    ["path", {"d":"m4 10 1.5 2L4 14"}],
    ["path", {"d":"m7 21 3-6-1.5-3"}],
    ["path", {"d":"m7 3 3 6h4"}],
  ],
  "Sparkles": [
    ["path", {"d":"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"}],
    ["path", {"d":"M20 2v4"}],
    ["path", {"d":"M22 4h-4"}],
    ["circle", {"cx":"4","cy":"20","r":"2"}],
  ],
  "Sprout": [
    ["path", {"d":"M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3"}],
    ["path", {"d":"M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4"}],
    ["path", {"d":"M5 21h14"}],
  ],
  "Sun": [
    ["circle", {"cx":"12","cy":"12","r":"4"}],
    ["path", {"d":"M12 2v2"}],
    ["path", {"d":"M12 20v2"}],
    ["path", {"d":"m4.93 4.93 1.41 1.41"}],
    ["path", {"d":"m17.66 17.66 1.41 1.41"}],
    ["path", {"d":"M2 12h2"}],
    ["path", {"d":"M20 12h2"}],
    ["path", {"d":"m6.34 17.66-1.41 1.41"}],
    ["path", {"d":"m19.07 4.93-1.41 1.41"}],
  ],
  "SunMedium": [
    ["circle", {"cx":"12","cy":"12","r":"4"}],
    ["path", {"d":"M12 3v1"}],
    ["path", {"d":"M12 20v1"}],
    ["path", {"d":"M3 12h1"}],
    ["path", {"d":"M20 12h1"}],
    ["path", {"d":"m18.364 5.636-.707.707"}],
    ["path", {"d":"m6.343 17.657-.707.707"}],
    ["path", {"d":"m5.636 5.636.707.707"}],
    ["path", {"d":"m17.657 17.657.707.707"}],
  ],
  "Sunrise": [
    ["path", {"d":"M12 2v8"}],
    ["path", {"d":"m4.93 10.93 1.41 1.41"}],
    ["path", {"d":"M2 18h2"}],
    ["path", {"d":"M20 18h2"}],
    ["path", {"d":"m19.07 10.93-1.41 1.41"}],
    ["path", {"d":"M22 22H2"}],
    ["path", {"d":"m8 6 4-4 4 4"}],
    ["path", {"d":"M16 18a4 4 0 0 0-8 0"}],
  ],
  "Sunset": [
    ["path", {"d":"M12 10V2"}],
    ["path", {"d":"m4.93 10.93 1.41 1.41"}],
    ["path", {"d":"M2 18h2"}],
    ["path", {"d":"M20 18h2"}],
    ["path", {"d":"m19.07 10.93-1.41 1.41"}],
    ["path", {"d":"M22 22H2"}],
    ["path", {"d":"m16 6-4 4-4-4"}],
    ["path", {"d":"M16 18a4 4 0 0 0-8 0"}],
  ],
  "Thermometer": [
    ["path", {"d":"M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z"}],
  ],
  "ThermometerSun": [
    ["path", {"d":"M12 2v2"}],
    ["path", {"d":"M12 8a4 4 0 0 0-1.645 7.647"}],
    ["path", {"d":"M2 12h2"}],
    ["path", {"d":"M20 14.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0z"}],
    ["path", {"d":"m4.93 4.93 1.41 1.41"}],
    ["path", {"d":"m6.34 17.66-1.41 1.41"}],
  ],
  "Trash2": [
    ["path", {"d":"M10 11v6"}],
    ["path", {"d":"M14 11v6"}],
    ["path", {"d":"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"}],
    ["path", {"d":"M3 6h18"}],
    ["path", {"d":"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"}],
  ],
  "TrendingUp": [
    ["path", {"d":"M16 7h6v6"}],
    ["path", {"d":"m22 7-8.5 8.5-5-5L2 17"}],
  ],
  "Umbrella": [
    ["path", {"d":"M12 13v7a2 2 0 0 0 4 0"}],
    ["path", {"d":"M12 2v2"}],
    ["path", {"d":"M20.992 13a1 1 0 0 0 .97-1.274 10.284 10.284 0 0 0-19.923 0A1 1 0 0 0 3 13z"}],
  ],
  "Users": [
    ["path", {"d":"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"}],
    ["path", {"d":"M16 3.128a4 4 0 0 1 0 7.744"}],
    ["path", {"d":"M22 21v-2a4 4 0 0 0-3-3.87"}],
    ["circle", {"cx":"9","cy":"7","r":"4"}],
  ],
  "Volume2": [
    ["path", {"d":"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z"}],
    ["path", {"d":"M16 9a5 5 0 0 1 0 6"}],
    ["path", {"d":"M19.364 18.364a9 9 0 0 0 0-12.728"}],
  ],
  "VolumeX": [
    ["path", {"d":"M11 4.702a.7.7 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.7.7 0 0 0 11 19.298z"}],
    ["path", {"d":"m16.5 14.5 5-5"}],
    ["path", {"d":"m16.5 9.5 5 5"}],
  ],
  "Waves": [
    ["path", {"d":"M2 12q2.5 2 5 0t5 0 5 0 5 0"}],
    ["path", {"d":"M2 19q2.5 2 5 0t5 0 5 0 5 0"}],
    ["path", {"d":"M2 5q2.5 2 5 0t5 0 5 0 5 0"}],
  ],
  "Wheat": [
    ["path", {"d":"M2 22 16 8"}],
    ["path", {"d":"M3.47 12.53 5 11l1.53 1.53a3.5 3.5 0 0 1 0 4.94L5 19l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z"}],
    ["path", {"d":"M7.47 8.53 9 7l1.53 1.53a3.5 3.5 0 0 1 0 4.94L9 15l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z"}],
    ["path", {"d":"M11.47 4.53 13 3l1.53 1.53a3.5 3.5 0 0 1 0 4.94L13 11l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z"}],
    ["path", {"d":"M20 2h2v2a4 4 0 0 1-4 4h-2V6a4 4 0 0 1 4-4Z"}],
    ["path", {"d":"M11.47 17.47 13 19l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L5 19l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z"}],
    ["path", {"d":"M15.47 13.47 17 15l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L9 15l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z"}],
    ["path", {"d":"M19.47 9.47 21 11l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L13 11l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z"}],
  ],
  "Wifi": [
    ["path", {"d":"M12 20h.01"}],
    ["path", {"d":"M2 8.82a15 15 0 0 1 20 0"}],
    ["path", {"d":"M5 12.859a10 10 0 0 1 14 0"}],
    ["path", {"d":"M8.5 16.429a5 5 0 0 1 7 0"}],
  ],
  "WifiOff": [
    ["path", {"d":"M12 20h.01"}],
    ["path", {"d":"M8.5 16.429a5 5 0 0 1 7 0"}],
    ["path", {"d":"M5 12.859a10 10 0 0 1 5.17-2.69"}],
    ["path", {"d":"M19 12.859a10 10 0 0 0-2.007-1.523"}],
    ["path", {"d":"M2 8.82a15 15 0 0 1 4.177-2.643"}],
    ["path", {"d":"M22 8.82a15 15 0 0 0-11.288-3.764"}],
    ["path", {"d":"m2 2 20 20"}],
  ],
  "Wind": [
    ["path", {"d":"M12.8 19.6A2 2 0 1 0 14 16H2"}],
    ["path", {"d":"M17.5 8a2.5 2.5 0 1 1 2 4H2"}],
    ["path", {"d":"M9.8 4.4A2 2 0 1 1 11 8H2"}],
  ],
  "X": [
    ["path", {"d":"M18 6 6 18"}],
    ["path", {"d":"m6 6 12 12"}],
  ],
  "ZoomIn": [
    ["circle", {"cx":"11","cy":"11","r":"8"}],
    ["line", {"x1":"21","x2":"16.65","y1":"21","y2":"16.65"}],
    ["line", {"x1":"11","x2":"11","y1":"8","y2":"14"}],
    ["line", {"x1":"8","x2":"14","y1":"11","y2":"11"}],
  ],
  "ZoomOut": [
    ["circle", {"cx":"11","cy":"11","r":"8"}],
    ["line", {"x1":"21","x2":"16.65","y1":"21","y2":"16.65"}],
    ["line", {"x1":"8","x2":"14","y1":"11","y2":"11"}],
  ],
};

/** The family's own coordinate system. Both renderers must set exactly this viewBox. */
export const ICON_VIEW_BOX = "0 0 24 24" as const;

export function isIconName(value: string): value is IconName {
  return (ICON_NAMES as readonly string[]).includes(value);
}
