/**
 * Last-known-good snapshot shipped with the app binary.
 *
 * On first ever launch — or on first cold-start in airplane mode —
 * react-query-persist-client will see no persisted cache (empty AsyncStorage).
 * The initialData below seeds the query cache so the app is never blank
 * offline. This is the same payload the web reads at build time so mobile
 * and web stay in lockstep.
 *
 * The snapshot is regenerated by `npm run build:snapshot` (Phase 4 CI job
 * will run this as a prebuild step). For local dev we hand-author the file
 * from MOCK_ALERTS so the pipeline works before CI wiring exists.
 */

import type { AlertItemType } from '@hazardnet/core';
import { MOCK_ALERT_ROWS } from '../../src/lib/mockAlerts';

export interface SnapshotEnvelope {
  schemaVersion: number;
  generatedAt: string;
  alerts: AlertItemType[];
  disclaimer: string;
}

export const LAST_KNOWN_GOOD: SnapshotEnvelope = {
  schemaVersion: 1,
  generatedAt: '2026-09-24T00:00:00Z',
  alerts: MOCK_ALERT_ROWS,
  disclaimer:
    'Last-known-good snapshot. Data may be older than the live feed. Follow instructions from BMD, FFWC, DDM and your local administration.',
};
