/**
 * GENERATED by scripts/build-brand-assets.mjs — do not edit. Re-run the script; `--check` (and the test suite)
 * fail if this file drifts from scripts/lib/infinity-geometry.mjs.
 */
export const INFINITY = {
  viewBox: '-60 -30 120 60',
  loaderViewBox: '-64 -36 128 72',
  strokeWidth: 10,
  halfWidth: 56,
  full: 'M-15.3 -14.997L15.3 14.997A21 21 0 1 0 15.3 -14.997L-15.3 14.997A21 21 0 1 1 -15.3 -14.997Z',
  under: 'M15.3 14.997A21 21 0 1 0 15.3 -14.997L-15.3 14.997A21 21 0 1 1 -15.3 -14.997',
  over: 'M-15.3 -14.997L15.3 14.997',
  cut: { x: -12, y: -8, width: 24, height: 16, rotate: 44.427 },
  apex: { left: [-51, 0], right: [51, 0] },
  gradient: [[0,"#0064E0"],[0.55,"#1A7BF5"],[1,"#3D93FA"]],
  lap: 2.6,
} as const;
