/**
 * GENERATED by scripts/build-brand-assets.mjs — do not edit. Re-run the script; `--check` (and the test suite)
 * fail if this file drifts from scripts/lib/infinity-geometry.mjs.
 */
export const INFINITY = {
  viewBox: '-60 -30 120 60',
  loaderViewBox: '-64 -36 128 72',
  strokeWidth: 10,
  halfWidth: 56,
  full: 'M-15.3 -14.997L15.3 14.997A21 21 0 1 0 15.3 -14.997L-15.3 14.997A21 21 0 1 1 -15.3 -14.997Z',
  under: 'M15.3 14.997A21 21 0 1 0 15.3 -14.997L-15.3 14.997A21 21 0 1 1 -15.3 -14.997',
  over: 'M-15.3 -14.997L15.3 14.997',
  cut: { x: -12, y: -8, width: 24, height: 16, rotate: 44.427 },
  apex: { left: [-51, 0], right: [51, 0] },
  gradient: [[0,"#0064E0"],[0.55,"#1A7BF5"],[1,"#3D93FA"]],
  lap: 2.6,
  /** Comet layers, longest first: their HEADS line up (see layerDelay in the loader SVG). */
  layers: [{"name":"tail","len":24,"opacity":0.3,"color":"#0064E0","width":10},{"name":"mid","len":14,"opacity":0.65,"color":"#1A7BF5","width":10},{"name":"head","len":6,"opacity":1,"color":"#3D93FA","width":10},{"name":"core","len":2.4,"opacity":0.95,"color":"#FFFFFF","width":4}],
  /** Where the apex nodes sit on the closed path, as a percentage of its length. */
  fraction: {"rightApex":32.576,"leftApex":82.576},
} as const;
