import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Breadcrumbs from '../components/Breadcrumbs';
import { usePageSeo } from '../hooks/usePageSeo';

export const Terms: React.FC = () => {
  // Per-route <head>: the prerenderer writes these into the static HTML, but a
  // client-side transition needs the hook to keep title/canonical/robots correct.
  usePageSeo('/terms');
  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, ease: 'easeOut' }}
      className="space-y-8 max-w-4xl mx-auto"
    >
      <Breadcrumbs />

      <div className="max-w-[65ch] space-y-6 border border-carbon-20 bg-white p-6 text-base leading-[1.62] text-carbon-70 lg:p-8">
        
        <div className="border-b border-carbon-20 pb-4 space-y-2">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-sm text-xs font-mono font-bold bg-nasa-red/10 text-nasa-red-shade border border-nasa-blue/20 uppercase">
              Legal Agreement
            </span>
            <span className="text-carbon-30">•</span>
            <span className="text-xs text-carbon-60 font-medium">Effective Date: August 1, 2026</span>
          </div>

          <h1 className="text-[28px] font-bold leading-[1.2] tracking-tight text-carbon-90">
            HazardNet AI Terms of Service & Data License
          </h1>
        </div>

        <section className="space-y-2">
          <h2 className="text-[22px] font-bold tracking-tight text-carbon-90">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the HazardNet AI web platform, mobile applications, or API endpoints, you agree to be bound by these Terms and Conditions. HazardNet is a hosted disaster early-warning initiative and decision support system.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-[22px] font-bold tracking-tight text-carbon-90">2. Hosted Model Protection</h2>
          <p>
            HazardNet model weights, preprocessing parameters, and inference implementation are proprietary server-side assets. The web platform exposes prediction results through authorized API requests only; downloading, reverse engineering, scraping, or attempting to reconstruct protected model assets is prohibited.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-[22px] font-bold tracking-tight text-carbon-90">3. Disaster Early-Warning Disclaimer</h2>
          <p className="border-l-2 border-nasa-orange bg-white p-4 text-carbon-80">
            <strong>Important Notice:</strong> HazardNet satellite AI predictions, continuous severity indexes, and 72-hour agronomic advisories are generated by automated neural network models for decision support. They do not supersede or replace official emergency evacuation orders, cyclone warnings, or river level bulletins issued by the Bangladesh Meteorological Department (BMD) or the Flood Forecasting & Warning Centre (FFWC).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-[22px] font-bold tracking-tight text-carbon-90">4. API Usage & Rate Limits</h2>
          <p>
            Public REST API endpoints and WASM model assets are subject to rate limits (1,000 requests per day for standard users) to preserve infrastructure availability during emergency hazard events. Unauthorized automated scraping or denial-of-service attempts will result in IP blocklisting.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-[22px] font-bold tracking-tight text-carbon-90">5. Contact & Questions</h2>
          <p>
            For legal or academic licensing inquiries, please visit our <Link to="/contact" className="font-bold text-nasa-blue-shade underline underline-offset-4">Contact Page</Link> or view our <Link to="/privacy" className="font-bold text-nasa-blue-shade underline underline-offset-4">Privacy Policy</Link>.
          </p>
        </section>

      </div>

    </motion.div>
  );
};

export default Terms;
