import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Breadcrumbs from '../components/Breadcrumbs';

export const Terms: React.FC = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, ease: 'easeOut' }}
      className="space-y-8 max-w-4xl mx-auto"
    >
      <Breadcrumbs />

      <div className="bg-white border border-slate-200 rounded-2xl p-6 md:p-8 shadow-xs space-y-6 text-xs text-slate-700 leading-relaxed">
        
        <div className="border-b border-slate-200 pb-4 space-y-2">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-nasa-red/10 text-nasa-red-shade border border-nasa-blue/20 uppercase">
              Legal Agreement
            </span>
            <span className="text-slate-300">•</span>
            <span className="text-xs text-slate-500 font-medium">Effective Date: August 1, 2026</span>
          </div>

          <h1 className="text-2xl font-extrabold text-slate-900">
            HazardNet AI Terms of Service & Data License
          </h1>
        </div>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the HazardNet AI web platform, mobile applications, or API endpoints, you agree to be bound by these Terms and Conditions. HazardNet is a hosted disaster early-warning initiative and decision support system.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">2. Hosted Model Protection</h2>
          <p>
            HazardNet model weights, preprocessing parameters, and inference implementation are proprietary server-side assets. The web platform exposes prediction results through authorized API requests only; downloading, reverse engineering, scraping, or attempting to reconstruct protected model assets is prohibited.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">3. Disaster Early-Warning Disclaimer</h2>
          <p className="p-3 bg-amber-50 border border-amber-200 text-amber-900 rounded-xl">
            <strong>Important Notice:</strong> HazardNet satellite AI predictions, continuous severity indexes, and 72-hour agronomic advisories are generated by automated neural network models for decision support. They do not supersede or replace official emergency evacuation orders, cyclone warnings, or river level bulletins issued by the Bangladesh Meteorological Department (BMD) or the Flood Forecasting & Warning Centre (FFWC).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">4. API Usage & Rate Limits</h2>
          <p>
            Public REST API endpoints and WASM model assets are subject to rate limits (1,000 requests per day for standard users) to preserve infrastructure availability during emergency hazard events. Unauthorized automated scraping or denial-of-service attempts will result in IP blocklisting.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">5. Contact & Questions</h2>
          <p>
            For legal or academic licensing inquiries, please visit our <Link to="/contact" className="text-amber-800 font-bold underline">Contact Page</Link> or view our <Link to="/privacy" className="text-amber-800 font-bold underline">Privacy Policy</Link>.
          </p>
        </section>

      </div>

    </motion.div>
  );
};

export default Terms;
