// POST /api/v1/telemetry — the receiving end of @hazardnet/analytics.
//
// Deployed through the existing `api/v1/[resource].js` entry point, so it costs **no new
// Vercel function** (the Hobby plan allows 12 — see
// docs/codebase/ARCHITECTURE.md#vercel-serverless-surface-the-12-function-budget).
//
// The design constraint is that this is an **anonymous, unauthenticated, write-only**
// endpoint that any browser can call: it is the one surface where a stranger's bytes reach
// the deployment. So it accepts a narrow shape and nothing else — an allowlist rather than
// a schema-validation library, because the whole point is that an attacker who finds it
// cannot make it store or reflect anything:
//
//   - `sessionId` — opaque, short, generated by the client.
//   - `events[]` — at most 50 per batch, each with a bounded name, a bounded property
//     object of scalars only, and a timestamp.
//
// There is **no persistence here**: the handler validates and acknowledges. Events are
// emitted to the platform log (`console.log` on Vercel → log drains) where they can be
// forwarded to a real sink by whoever operates the project. Wiring a durable store is an
// owner action (docs/ops/owner-actions.md): writing anonymous analytics into Firestore
// from an unauthenticated endpoint would be a data-integrity and cost decision, not a
// technical one.

import { guardRequest } from '../../backend/middleware/serverlessGuard.js';

const MAX_EVENTS_PER_BATCH = 50;
const MAX_EVENT_NAME_LENGTH = 64;
const MAX_SESSION_ID_LENGTH = 64;
const MAX_PROPERTY_KEYS = 20;
const MAX_PROPERTY_VALUE_LENGTH = 256;
const MAX_BODY_BYTES = 64 * 1024;

const EVENT_NAME_RE = /^[a-z0-9][a-z0-9_.]{0,63}$/;

const isScalar = (value) =>
  typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' || value === null;

/** Return a cleaned, bounded copy of one event, or a string describing why it is refused. */
export function validateEvent(event) {
  if (!event || typeof event !== 'object' || Array.isArray(event)) return 'event must be an object';
  const name = typeof event.event === 'string' ? event.event.trim().toLowerCase() : '';
  if (!EVENT_NAME_RE.test(name) || name.length > MAX_EVENT_NAME_LENGTH) {
    return `invalid event name ${JSON.stringify(String(event.event).slice(0, 40))}`;
  }
  if (typeof event.at !== 'number' || !Number.isFinite(event.at)) return 'event.at must be a finite number';

  const properties = {};
  const source = event.properties && typeof event.properties === 'object' && !Array.isArray(event.properties)
    ? event.properties
    : {};
  const keys = Object.keys(source);
  if (keys.length > MAX_PROPERTY_KEYS) return `too many properties (${keys.length} > ${MAX_PROPERTY_KEYS})`;
  for (const key of keys) {
    if (key.length > MAX_EVENT_NAME_LENGTH) return `property key too long: ${key.slice(0, 20)}…`;
    const value = source[key];
    if (!isScalar(value)) return `property ${key} must be a string, number, boolean or null`;
    if (typeof value === 'string' && value.length > MAX_PROPERTY_VALUE_LENGTH) {
      return `property ${key} exceeds ${MAX_PROPERTY_VALUE_LENGTH} characters`;
    }
    // Numbers must survive JSON round-trips; NaN/Infinity serialise to `null` silently.
    if (typeof value === 'number' && !Number.isFinite(value)) return `property ${key} is not a finite number`;
    properties[key] = value;
  }

  return { event: name, properties, at: event.at };
}

/** Validate a whole batch. Returns `{ ok: true, batch }` or `{ ok: false, error }`. */
export function validateTelemetryBatch(payload) {
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) return { ok: false, error: 'body must be a JSON object' };

  const sessionId = typeof payload.sessionId === 'string' ? payload.sessionId.trim() : '';
  if (!sessionId || sessionId.length > MAX_SESSION_ID_LENGTH) return { ok: false, error: 'sessionId must be a 1–64 character string' };

  if (!Array.isArray(payload.events)) return { ok: false, error: 'events must be an array' };
  if (payload.events.length === 0) return { ok: false, error: 'events must not be empty' };
  if (payload.events.length > MAX_EVENTS_PER_BATCH) {
    return { ok: false, error: `too many events (${payload.events.length} > ${MAX_EVENTS_PER_BATCH})` };
  }

  const events = [];
  for (const [index, event] of payload.events.entries()) {
    const validated = validateEvent(event);
    if (typeof validated === 'string') return { ok: false, error: `events[${index}]: ${validated}` };
    events.push(validated);
  }

  return { ok: true, batch: { sessionId, events } };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('allow', 'POST');
    res.status(405).json({ error: 'Method Not Allowed' });
    return;
  }
  // Anonymous browsers hit this endpoint, so it gets the tightest bucket in the guard.
  if (guardRequest(req, res, { bucket: 'ai' })) return;

  const parsed = typeof req.body === 'string' ? safeJson(req.body) : req.body;
  if (parsed === undefined) {
    res.status(400).json({ error: 'body must be valid JSON' });
    return;
  }
  if (typeof req.body === 'string' && Buffer.byteLength(req.body, 'utf8') > MAX_BODY_BYTES) {
    res.status(413).json({ error: 'payload too large' });
    return;
  }

  const validated = validateTelemetryBatch(parsed);
  if (!validated.ok) {
    res.status(400).json({ error: validated.error });
    return;
  }

  // Log drains are the transport. One line per event keeps it greppable; the payload has
  // already been bounded above, so this cannot become a log-injection or cost problem.
  for (const event of validated.batch.events) {
    console.log(JSON.stringify({
      tag: 'analytics',
      session: validated.batch.sessionId.slice(0, 32),
      event: event.event,
      at: event.at,
      properties: event.properties,
    }));
  }

  res.setHeader('cache-control', 'no-store');
  res.status(204).end();
}

function safeJson(text) {
  try {
    return JSON.parse(text);
  } catch {
    return undefined;
  }
}
