/**
 * @jest-environment node
 */
/**
 * Model artifact handshake (ML-02) — regression guard.
 *
 * `Models/VERSION.json` is the file the backend reads for `model_version` in
 * `/health` and the `POST /api/predict` envelope. It was generated by
 * `scripts/gen-model-version.mjs` but never committed, so every environment
 * (CI, Vercel, the self-hosted backend) fell through to the legacy literal
 * `1.0-FP32 (legacy literal — VERSION.json missing)`. That literal has no
 * `x.y.z` in it, so `__tests__/api/predict.test.js` failed in CI
 * (expect.stringMatching(/\d+\.\d+\.\d+/)) on an otherwise green backend suite.
 *
 * The failure is invisible to a `git diff`-based CI gate — an untracked file
 * diffs clean — so it is pinned here from both ends:
 *   1. the file is present, well-formed, and its hashes match the artifacts
 *      currently on disk (i.e. it was regenerated after the last artifact
 *      change), and
 *   2. `getModelInfo()` actually returns it (not the legacy fallback).
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.join(__dirname, '..');
const VERSION_PATH = path.join(ROOT, 'Models', 'VERSION.json');

const EXPECTED_ARTIFACTS = [
  'hazardnet_fp32.tflite',
  'labels.json',
  'normalization_stats.json',
  'preprocessing_config.json',
];

const sha256 = (file) =>
  crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');

describe('Models/VERSION.json handshake', () => {
  test('is tracked in the repository (not just generated locally)', () => {
    expect(fs.existsSync(VERSION_PATH)).toBe(true);
  });

  test('carries a semver-shaped version the API contract can assert on', () => {
    const { version } = JSON.parse(fs.readFileSync(VERSION_PATH, 'utf8'));
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

    // Shape the API contract relies on (/\d+\.\d+\.\d+/ in
    // __tests__/api/predict.test.js) plus the package version the generator
    // derives it from — a bump to package.json must regenerate this file.
    expect(version).toMatch(/\d+\.\d+\.\d+/);
    expect(version.startsWith(`${pkg.version}+model.`)).toBe(true);
    expect(version).toMatch(/\+model\.[0-9a-f]{12}$/);
  });

  test('lists every shipped artifact with the hash of the file on disk', () => {
    const entry = JSON.parse(fs.readFileSync(VERSION_PATH, 'utf8'));
    const byName = Object.fromEntries(entry.artifacts.map((a) => [a.name, a]));

    for (const name of EXPECTED_ARTIFACTS) {
      const artifact = byName[name];
      expect(artifact).toBeDefined();
      const file = path.join(ROOT, 'Models', name);
      expect(fs.existsSync(file)).toBe(true);
      expect(artifact.bytes).toBe(fs.statSync(file).size);
      expect(artifact.sha256).toBe(sha256(file));
    }
  });

  test('getModelInfo() serves the file, never the legacy literal', () => {
    const { getModelInfo, LEGACY_VERSION } = require('../backend/modelInfo.js');
    const info = getModelInfo();

    expect(info.version).not.toBe(LEGACY_VERSION);
    const onDisk = JSON.parse(fs.readFileSync(VERSION_PATH, 'utf8'));
    expect(info.version).toBe(onDisk.version);
    expect(info.artifacts).toHaveLength(EXPECTED_ARTIFACTS.length);
  });
});
